#setting the variable: days
Days = "Mon Tue Wed Thur Fri Sat Sun"
#setting the variable: Months
Months = "Jan\nFeb\nMar\nApr\nJun\nJul\nAug\nSep\nOct\nNov\nDec"
#\n scoots the words down a line.
print("These are the days:", Days)
print("These are the months:", Months)
#the three double quotes allows you to put as much text as you want.
print("""
There is something going on here.
With the three double quotes,
We'll be able to type as much as we want
""")
